---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: prod
  targetNamespace: default

